version: "3.7"

services:
    backend:
        build:
            context: server
        command: npm run dev
        ports:
            - 8080:8080
        working_dir: /server/app
        volumes:
            - ./server:/server/app
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: brichard
            MYSQL_DB: matcha_db
        networks:
            - public
            - private
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        restart: always
        volumes:
            - ./matcha-mysql-data:/var/lib/mysql
            - ./server/db-scripts:/docker-entrypoint-initdb.d
        networks:
            - private
        environment:
            MYSQL_ROOT_PASSWORD: brichard
            MYSQL_DATABASE: matcha_db
    frontend:
        build:
            context: front
        ports:
            - 5173:5173
        working_dir: /front/src
        volumes:
            - ./front:/front/src
        networks:
            - public
        depends_on:
            - backend

networks:
    public:
    private:
volumes:
    matcha-mysql-data: