version: "3.8"

services:
    matcha_backend:
        container_name: matcha_backend
        build:
            context: server
        command: npm run dev
        ports:
            - 8080:8080
        working_dir: /server/app
        volumes:
            - ./server:/server/app
        environment:
            MYSQL_HOST: matcha_db
            MYSQL_USER: root
            MYSQL_PASSWORD: brichard
            MYSQL_DB: matcha_db
        networks:
            - public
            - private
        depends_on:
            - matcha_db
    matcha_db:
        container_name: matcha_db
        build:
            context: ./mysql
            dockerfile: ./Dockerfile
        restart: always
        volumes:
            - matcha-mysql-data:/var/lib/mysql
        networks:
            - private
        environment:
            MYSQL_ROOT_PASSWORD: brichard
            MYSQL_DATABASE: matcha_db
    matcha_frontend:
        container_name: matcha_frontend
        build:
            context: front
        ports:
            - 5173:5173
        working_dir: /front/src
        volumes:
            - ./front:/front/src
        networks:
            - public
        depends_on:
            - matcha_backend

networks:
    public:
    private:
volumes:
    matcha-mysql-data: