#!/bin/bash

VAR=$1
if test $VAR; then
    docker stop $VAR;
    docker-compose rm $VAR -f;
    docker-compose up -d $VAR;
else
    docker stop $(docker ps -a -q);
    docker rm $(docker ps -a -q);
    docker volume rm $(docker volume ls -q)
    docker-compose up -d;
fi;