#!/bin/bash

VAR=$1
if test $VAR; then
    docker stop $VAR;
    docker-compose rm $VAR -f;
    docker image rm env-$VAR;
    docker-compose up -d $VAR;
else
    docker-compose down;
    docker system prune --all -f --volumes;
    docker-compose up -d;
fi;